### ISSUE TITLE
Inventory - whitespace in names

### ISSUE THREAD

**Issue by Rina14** [JirkaDellOro/FUDGE_Story#11]
Im Namensattribut des Items sind Leerzeichen ungültig und führen daher zu einem Fehler in der Konsole. Somit ist das Inventar nicht mehr funktionsfähig.

**Comment by JirkaDellOro** [comment]
Für die ids der Elemente im Inventory werden jetzt Leerzeichen durch Unterstriche ersetzt.
_item.name.replaceAll(" ", "_")

**Comment by Rina14** [comment]
Leerzeichen sind nun auch im Namen des Items gültig. Getestet und hat geklappt.
