### ISSUE TITLE
setData und setDataInterface Konflikt

### ISSUE THREAD

**Issue by Rina14** [JirkaDellOro/FUDGE_Story#12]
Der Meter lässt sich ohne Auskommentieren von setData nicht visualisiert füllen bzw. leeren.

**Comment by JirkaDellOro** [comment]
Ich habe nun setData und setDataInterface zu einer Methode setData zusammengefasst, die als zweiten Parameter optional ein HTMLElement für das Interface entgegen nimmt. Bitte testen.

Ich habe mich dagegen entschieden, verschachtelte Objekte im Interface darzustellen. Falls das einmal dringend erforderlich sein sollte, würde ich FudgeUserInterface einbinden, da ist das schon drin. Derzeit scheint mir es aber übertrieben. Sinnvoller sollten wir Progress-Data auf "flache" Objekte beschränken und die Information nur durch die Schlüssel strukturieren, z.B. scoreNPC2 etc.

**Comment by JirkaDellOro** [comment]
Mehrere Meter sind übrigens möglich, hier war ein Fehler in der HTML-Datei. Meter braucht einen schließenden Tag...

**Comment by Rina14** [comment]
Ja, beim Meter gab es auch keine Probleme, was die Anzahl betrifft.


> Ich habe nun setData und setDataInterface zu einer Methode setData zusammengefasst, die als zweiten Parameter optional ein HTMLElement für das Interface entgegen nimmt. Bitte testen.
> 
> Ich habe mich dagegen entschieden, verschachtelte Objekte im Interface darzustellen. Falls das einmal dringend erforderlich sein sollte, würde ich FudgeUserInterface einbinden, da ist das schon drin. Derzeit scheint mir es aber übertrieben. Sinnvoller sollten wir Progress-Data auf "flache" Objekte beschränken und die Information nur durch die Schlüssel strukturieren, z.B. scoreNPC2 etc.

Getestet und hat alles geklappt!
