### ISSUE TITLE
Splashscreen dark-mode

### ISSUE THREAD

**Issue by Rina14** [JirkaDellOro/FUDGE_Story#13]
Der Splashscreen soll in einer weißen und dunklen Version zur Verfügung stehen. Daher wäre eine Einstellbarkeit des Modus super, sodass der Autor selbst entscheiden kann.

**Comment by JirkaDellOro** [comment]
Kommt der dunkle Rahmen noch?

**Comment by Rina14** [comment]
Nur die vorläufige Version (die ich Dir geschickt hatte), außer Du hast das Fudge-Logo in transparent und wir machen erstmal da nen dunklen Hintergrund rein. 

Ansonsten habe ich das nicht vergessen, donut worry.

**Comment by Rina14** [comment]
Hast Du mir noch die Schriftart?

**Comment by JirkaDellOro** [comment]
Leider nein :-(

**Comment by JirkaDellOro** [comment]
Doch, jetzt fällt es mir wieder ein. Es ist natürlich die HFU-Hausschrift: Univers 47 CondensedLight

**Comment by Rina14** [comment]
Mir stehen jetzt die Logos zur Verfügung! Darkmode kann kommen, yippie

**Comment by JirkaDellOro** [comment]
Damit sind wir wohl durch
