### ISSUE TITLE
Gesamtlautstärke regeln

### ISSUE THREAD

**Issue by Rina14** [JirkaDellOro/FUDGE_Story#15]
Mit der vorläufigen setVolume-Methode wird aktuell nur ein Sound beeinflusst. Das müsste so geändert werden, dass man eben die Gesamtlautstärke lauter und leiser machen kann. Aktuell wird das Ganze über Buttons gesteuert.

**Comment by Rina14** [comment]
Oder wenn es dadurch möglich wäre, später selbst im Menü festzulegen, ob die jeweilige Variable zum Sound oder bspw. die der Themes beeinflusst werden soll. So wäre dies in Music Volume sowie in Sound Volume getrennt handlebar und vorteilhafter. Ginge das bei der aktuellen Struktur überhaupt?

**Comment by JirkaDellOro** [comment]
Die setVolume-Methode wurde ausgetauscht gegen setMasterVolume, bitte ausprobieren.
```typescript
    /**
     * Set the overall volume for the sound mix
     */
    public static setMasterVolume(_volume: number): void {
         ƒ.AudioManager.default.volume = _volume;
    }
```
Den Master-Volume hatte ich damals bewusst nicht eingebaut, da ich annehme, dass die Leute heute wohl eher einfach die Gesamtlautstärke ihres Gerätes einstellen, als in einem Menü nach der Lautstärke einer bestimmten App zu suchen.

Verschiedene Soundgruppen zu handhaben ist machbar, wie alles. Natürlich bedeutet das für den Autor wieder mehr Einarbeitungsaufwand, weil er dann Gruppen mitdenken muss, und höhere Komplexität von FUDGE-Story. Wie machen das denn andere VN-Engines?

**Comment by JirkaDellOro** [comment]
Passt das so oder brauchen wir mehr?

**Comment by Rina14** [comment]
das passt erstmal so, danke Dir. Bzgl. der Soundgruppen eröffne ich lieber erst einmal eine Diskussion, scheint mir sinnvoller.
