### ISSUE TITLE
Nicht verbrauchbare Items

### ISSUE THREAD

**Issue by SamuelKasper** [JirkaDellOro/FUDGE_Story#16]
Ich bräuchte das Feature Items eine Eigenschaft zu geben, durch welche sie nicht mehr verbraucht werden können.
In meiner Visual Novel soll es möglich sein, Fotos im Inventar zu lagern und immer wieder anzuschauen.

**Comment by JirkaDellOro** [comment]
Du kannst bei der Item-Definition nun noch einer Eigenschaft `static` den Wert `true` zuweisen. Probier' mal und schließe den Issue, wenn's klappt.
