### ISSUE TITLE
Klickabfang im Inventar

### ISSUE THREAD

**Issue by SebiPf** [JirkaDellOro/FUDGE_Story#17]
Eine Funktion die abfängt welches Item im Inventar angeklickt wurde um als Resultat ein Event auszulösen(z.b. eine Variable wird geändert).
Also z.b. wenn man ein Trank anklickt wird er benutzt und als Resultat wird eine Variable(Lebenspunkte) um 5 oder so erhöht.

**Comment by JirkaDellOro** [comment]
Das Inventar liefert dir als "Ergebnis" die verbrauchten Items, die musst Du auswerten. Oder geht es dir darum, dass das Inventar offen bleibt, während Du die Klicks auswertest?

**Comment by SebiPf** [comment]
Wie werte ich die aus? Ich hab dazu nirgends was gefunden. Das einzige auf das ich gekommen bin wäre was im fudgestory.js zu ändern aber da wollte ich mich erstmal nicht dran wagen.

**Comment by JirkaDellOro** [comment]
Schau mal was da in der Console rauspurzelt

`console.log(await ƒS.Inventory.open());`

**Comment by SebiPf** [comment]
ja gut da wird mir was ausgegeben wie ich das abfang ist aber trotzdem nicht klar und sehr entwicklerfreundlich(intuitiv) ist die Ausgabe auch nicht also ich will ja nicht in jeder Szene die ganze zeit überprüfen ob das gemacht wurde.

**Comment by Rina14** [comment]
Genau, der Ort der Auswertung wäre das Inventar. Durch den mit Klick ausgelöstem Konsum des Items werden Events ausgelöst, wie z.B. health+5. Somit wäre das Inventar währenddessen durchgehend geöffnet.

**Comment by Rina14** [comment]
& ja, das Inventar wird per Tastendruck geöffnet

**Comment by JirkaDellOro** [comment]
> Somit wäre das Inventar währenddessen durchgehend geöffnet  

Das wäre die entscheidende Information, nach der ich gefragt hatte.

**Comment by Rina14** [comment]
Jetzt hast Du sie :p

**Comment by JirkaDellOro** [comment]
Dann würde ich vorschlagen, dass man bei der Item-Definition optional noch einen Handler mitgeben kann, der bei Pointer-Up und Pointer-Down aufgerufen wird. Der empfängt ein Custom-Event mit dem Item-Namen als Datenlast. Dann kann man sich einen Handler bauen und dort machen, was man will, auch während das Inventar geöffnet ist.

**Comment by SebiPf** [comment]
das hört sich doch gut an

**Comment by JirkaDellOro** [comment]
Ok, da muss ich mir Gedanken über eine gute Struktur dafür machen. Was habt ihr bislang mit Signalen gemacht, vielleicht bietet sich das an.

**Comment by Rina14** [comment]
Lediglich kurze Verzögerungen eingebaut.

**Comment by JirkaDellOro** [comment]
Ok, stinknormale Handler passen besser. Ist eingebaut, bitte testen. Beispiel:

```typescript
    {
      name: "Fudge Item",
      description: "A delicious cube of fudge, adds 10 to your health",
      image: "Images/Fudge_48.png",
      static: false,
      handler: hndItem
    }


  function hndItem(_event: CustomEvent): void {
    console.log(_event);
  }
```

_event.type kann die Werte pointerUp oder pointerDown haben, den Namen des Items findet man in _event.detail

**Comment by SebiPf** [comment]
okay also ich hab das jetzt getestet und für meine zwecke funktioniert es perfekt

**Comment by SamuelKasper** [comment]
Ich glaube, dass der Handler zurzeit nicht optional ist. Ich bekomme einen Error, da ich den Handler nicht verwende. Wäre cool, wenn das noch geändert werden könnte.

**Comment by Rina14** [comment]
jetzt ist er optional
@JirkaDellOro

**Comment by JirkaDellOro** [comment]
Ups... vergessen. Danke!
