### ISSUE TITLE
Nicht-konsumierbare Items

### ISSUE THREAD

**Issue by Rina14** [JirkaDellOro/FUDGE_Story#18]
Alle Items sind derzeit konsumierbare Items. Hier soll aber zwischen konsumierbaren sowie nicht-konsumierbaren Items unterschieden werden. Wie kann/könnte man Items daher fixieren, sodass der Spieler diese nicht aufbrauchen kann?

#17

**Comment by JirkaDellOro** [comment]
Haben wir doch schon, siehe #16

**Comment by Rina14** [comment]
ahh ups, hab ich gar nicht gesehen und keine Benachrichtigung bekommen dazu. Super :)

**Comment by Rina14** [comment]
ok Benachrichtigung ist im Spam gelandet, grad gesehen...
