### ISSUE TITLE
Tastendruck und Klicks ohne Story Fortschritt

### ISSUE THREAD

**Issue by SamuelKasper** [JirkaDellOro/FUDGE_Story#19]
Das Öffnen/ Schließen des Inventars (über eine Taste), sowie auch das Betätigen der Buttons des ingame Menüs führt dazu, dass die Visual Novel inhaltlich weiter läuft. Wäre es möglich das voranschreiten der Novel beim Betätigen bestimmter Tasten / klicken des Menüs zu unterbinden?
Es wäre super, wenn man selbst festlegen könnte, bei welchen Tasten die Story nicht weiter gehen soll. Ich habe beispielsweise Features auf den Tasten I (Inventar öffnen / schließen), M (Menü ein/ausblenden) und T (Textbox ein/ausblenden). Beim Drücken dieser Tasten sollte kein „klick“ ausgelöst werden.

**Comment by JirkaDellOro** [comment]
Das sollte alles per `await` zu regeln sein, funktioniert da etwas nicht?

**Comment by SamuelKasper** [comment]
Wo müsste ich das await in diesem Fall denn reinpacken?
![grafik](https://user-images.githubusercontent.com/64090949/124350817-1a533d80-dbf7-11eb-8286-5ac7e22364c1.png)
![grafik](https://user-images.githubusercontent.com/64090949/124350839-348d1b80-dbf7-11eb-96ce-02744b35c0b2.png)

Wenn ich beim Inventar öffnen/ schließen await vorne drann packe bekomme ich beim Schließen des Inventars den folgenden Error:
![grafik](https://user-images.githubusercontent.com/64090949/124350965-f8a68600-dbf7-11eb-8978-12416744f1b5.png)
![grafik](https://user-images.githubusercontent.com/64090949/124351003-2a1f5180-dbf8-11eb-9d9e-fb92c48b8603.png)

**Comment by JirkaDellOro** [comment]
1. im oberen Bild macht es den Anschein, dass Du ein ganz eigenes Menüsystem gebastelt hast und nicht das von FUDGE-Story verwendest, Dann ergibt `await` keinen Sinn.
2. im unteren Bild passt 
  1. das `await` bei close nicht, weil close keine asynchrone Funktion ist
  2. laut der Fehlermeldung es nicht, dass das Menü bereits geöffnet wurde. Hast Du es im HTML mit open versehen?

**Comment by SamuelKasper** [comment]
Zu 1: Ich habe schon das FUDGE-Story Menü benutzt. An der Stelle möchte ich es nur per Tastendruck aus / einblenden, weswegen ich mir per getElementsByClassName das Menü Element hole, um es bearbeiten zu können.

Zu 4: Das Öffnen des Inventars hatte mit dem Code aus dem Bild funktioniert. Die Fehlermeldung kam erst, nachdem ich es durch erneuten Druck auf die I-Taste wieder schließen wollte.
(open hab ich nicht benutzt.)
![image](https://user-images.githubusercontent.com/64090949/124424753-e4819680-dd67-11eb-895c-462460ce9fa9.png)

Wenn ich die awaits beim Inventar wegmache, funktioniert das mit dem schließen und öffnen auch so wie es soll, am code an sich sollte es also eigentlich nicht liegen.

**Comment by Rina14** [comment]
> Das Öffnen/ Schließen des Inventars (über eine Taste), sowie auch das Betätigen der Buttons des ingame Menüs führt dazu, dass die Visual Novel inhaltlich weiter läuft. Wäre es möglich das voranschreiten der Novel beim Betätigen bestimmter Tasten / klicken des Menüs zu unterbinden?
> Es wäre super, wenn man selbst festlegen könnte, bei welchen Tasten die Story nicht weiter gehen soll. Ich habe beispielsweise Features auf den Tasten I (Inventar öffnen / schließen), M (Menü ein/ausblenden) und T (Textbox ein/ausblenden). Beim Drücken dieser Tasten sollte kein „klick“ ausgelöst werden.

@SamuelKasper @JirkaDellOro 
Die Szene soll nicht bei bestimmtem Tastendruck gesperrt sein, sondern die Szene soll generell nicht weiterlaufen, wenn Buttons des Menüs oder des Inventars betätigt werden. Sprich, diese sollen nicht als "Weiter-Per-Klick" für die Szene gewertet werden.

**Comment by JirkaDellOro** [comment]
Ah... dann geht es eigentlich gar nicht um das Menü sondern darum, wann die Story fortsetzt. Bzw. wie es implementiert ist, dass die Story stoppt. @SamuelKasper : wie machst Du das gerade?

@Rina14 : wie hatten wir das in der ersten Version gemacht, wo man einen Text durchblättern konnte?

**Comment by SamuelKasper** [comment]
Naja, also aktuell stoppt die Story bei mir ja nicht, wenn ich irgendeine Taste drücke oder das Menü benutze.

**Comment by JirkaDellOro** [comment]
Also sie pausiert erst gar nicht? Oder sie beendet die Pause sobald Du eine Taste drückst oder das Menü benutzt?

Poste bitte Links zu Quellcode auf Github und zur App auf Pages

**Comment by SamuelKasper** [comment]
Der Text / die Story läuft bei mir weiter, wenn ich eine Taste drücke, bzw. das Inventar öffne/schließe (Taste I) oder auf das Menü (Speichern/Laden/Steuerung/Credits) klicke. 

Quellcode:
https://github.com/SamuelKasper/VisualNovelEndabgabe/tree/main/Endabgabe/Source

Die Tastenabfragen / Menü sind in der Main:
https://github.com/SamuelKasper/VisualNovelEndabgabe/blob/main/Endabgabe/Source/Main.ts

Pages:
https://samuelkasper.github.io/VisualNovelEndabgabe/Endabgabe/index.html

**Comment by Rina14** [comment]
> Ah... dann geht es eigentlich gar nicht um das Menü sondern darum, wann die Story fortsetzt. Bzw. wie es implementiert ist, dass die Story stoppt. @SamuelKasper : wie machst Du das gerade?
> 
> @Rina14 : wie hatten wir das in der ersten Version gemacht, wo man einen Text durchblättern konnte?

Genau und wie Samuel schon gesagt hat, es funktioniert bei ihm nicht bzw. bei keinem. 

Das war mit progress und einer do-while Schleife gelöst worden, ist auch unter Tutorial in der Szene NovelPages nochmal drin. Bin mir gerade aber nicht mehr sicher, warum wir progress (dataForSave) benutzt hatten, glaube das kann weggelassen werden.

**Comment by Rina14** [comment]
@JirkaDellOro Wenn Du Dein Example durchgehst ist es ja genau das selbe Problem mit dem inhaltlichen Weiterlaufen oder das Tutorial etc.

**Comment by JirkaDellOro** [comment]
Ok, ich denke, ich weiß jetzt, worauf ihr hinaus wollt. Ich habe eine neue Version gebastelt, bei der die Pointer-Events von Menü und Inventar nicht weiter propagiert werden, bitte testen. 

Was die Tastaturkommandos betrifft, ist die Sache ein wenig komplizierter, da es derzeit ja explizit so implementiert ist, dass jede Taste ein "weiter" darstellt. Es kann nicht festgestellt werden, ob die Taste noch eine weitere Funktion hat und nicht mehr das Standardverhalten aufweisen soll. Hier bitte folgendes probieren:
- im Handler `_event.stopPropagation()` aufrufen, wenn das Tastaturevent nicht weitergeleitet und das Standardverhalten auslösen soll. Ich schätze aber, dass es dann schon zu spät ist und das Standardverhalten schon ausgelöst wurde, daher
- die Tastenfunktionalität mit `document.addEventListener("keydown", hndKeypress, true);` als Handler registrieren, Durch den dritten Parameter wird der Listener bereits in der capture-Phase aktiviert und ruft den Handler auf

Alternativ könnte man auch die Tasten mit Standardverhalten einschränken, in dem man Speech.signalNext überschreibt.

**Comment by Rina14** [comment]
Dass jede Taste ein "weiter" darstellt, finde ich problematisch und ist eher unüblich. Besser fände ich es, wenn ausschließlich die Leertaste neben dem Klick als "weiter" gezählt wird. Wäre das nicht einfacher?

**Comment by SamuelKasper** [comment]
Hab mir eben mal die neuste Fudge-Story Version gezogen und ausprobiert, allerdings löst das benutzen des Menüs nach wie vor einen "klick" aus.

**Comment by JirkaDellOro** [comment]
Oh... ich hatte das nur in der simplen getInput-Methode implementiert und nicht im statischen Menü. Bitte nochmal testen jetzt,

**Comment by SamuelKasper** [comment]
Klappt jetzt. Das Menü löst keinen "klick" mehr aus.

**Comment by JirkaDellOro** [comment]
> Dass jede Taste ein "weiter" darstellt, finde ich problematisch und ist eher unüblich. Besser fände ich es, wenn ausschließlich die Leertaste neben dem Klick als "weiter" gezählt wird. Wäre das nicht einfacher?

Soll ich das mal so als Standard implementieren?

**Comment by Rina14** [comment]
Ja, bitte.

**Comment by JirkaDellOro** [comment]
Bitte testen

Es gibt nun zudem eine neue globale Funktion getKeypress(_code), der man einen Keycode mitgibt und die ein Promise liefert, das erfüllt wird, wenn die Taste gedrückt wird. Kann man z.B. mit `await` nutzen um auf eine spezifische Taste zu warten oder mit `()=>` in Progress.defineSignal um ein Signal zu definieren.

**Comment by SamuelKasper** [comment]
Ich habe zwar nicht ganz verstanden, wofür das getKeypress zuständig ist, bzw. wie ich es benutze, aber ich kann jetzt auf jeden Fall Inventar etc. öffnen, ohne das ein "Klick" ausgelöst wird. Funktioniert für mich jetzt so wie es soll.

**Comment by JirkaDellOro** [comment]
@Rina14 kann man dann hier schließen?

**Comment by Rina14** [comment]
@SamuelKasper die Syntax ist dieselbe wie beim Definieren eines Signals:

`let pressK: ƒS.Signal = ƒS.Progress.defineSignal([() => ƒS.getKeypress(ƒ.KEYBOARD_CODE.K)]);`

und dem jeweiligen Aufruf dann einfach:

`await pressK();`

Kann man dann z.B. in Kombination mit `ƒS.Text.print("Drücke K");` ankündigen

-------------------------------------------------------------

@JirkaDellOro Ja, alles getestet. Das ist schon deutlich besser jetzt ohne dem ständigen Weiter bei beliebigen Tasten. Vielen Dank!
