### ISSUE TITLE
move Transition

### ISSUE THREAD

**Issue by Rina14** [JirkaDellOro/FUDGE_Story#2]
Um Bilder z.B. von A nach B zu bewegen könnte man eine move Transition bzw. eine ganze MoveTransition() (Transition-Klasse) definieren, um abwechslungsreichere Bewegungen einbauen zu können. Dabei unterscheidet man zwischen

- move
- moveoutright, moveoutleft, moveouttop, moveoutbottom
- moveinright, moveinleft, moveintop, moveinbottom

Bei der move Transition wird das Bild zur gewünschten Position (xpos, ypos) innerhalb von 0,5s (Standard) hinbewegt. Bei den anderen wird das Bild dabei von der jeweiligen Seite aus ins Bild ein- oder aus dem Bild ausgeblendet. Ist nun auch alles in der Analyseforderung drin. Wäre auch für das Spielerlebnis ziemlich schön, das drin zu haben.

**Bezieht sich auf Charaktere.**

**Comment by Rina14** [comment]
Bei folgenden Motions bzw. Animationen in FS ist es nicht möglich, Objekte, in dem Fall Charaktere, mit lediglich einer Animation in die Szene einzuspielen bzw. diese mit einem zusätzlichen `hide `animiert auszublenden. 

- moveoutright, moveoutleft, moveouttop, moveoutbottom
- moveinright, moveinleft, moveintop, moveinbottom

**Comment by JirkaDellOro** [comment]
Kapier' ich nicht. Diese Definitionen gibt es ja nicht in FS. Wie meinst Du das?

**Comment by Rina14** [comment]
Korrekt, allerdings sollte hier mit einer Animation der Charakter zuerst animiert werden und dann eben mithilfe von `hide` ausgeblendet. So könnte man genau diese Definitionen simulieren. Theoretisch zumindest. Praktisch reagiert der Charakter da leider nicht drauf.

**Comment by Rina14** [comment]
Das heißt, er wird nur "ausgefaded" mit dem `hide`. Die Animation spielt das Programm gar nicht erst vorher ab.

**Comment by JirkaDellOro** [comment]
Geht es also darum, zwei Animationen nacheinander abzuspielen?

**Comment by Rina14** [comment]
Nein, sondern Animation + hide-Methode

**Comment by JirkaDellOro** [comment]
Hast Du await genutzt?

**Comment by Rina14** [comment]
Ja:

```
    await ƒS.Character.animate(characters.Aoi, characters.Aoi.pose.normal, animation2);
    await ƒS.Character.hide(characters.Aoi);
```

**Comment by JirkaDellOro** [comment]
Achso... das ist ja so gar nicht vorgesehen. Es gibt keine vorgegebene Dauer für die Animation. Die `duration` gibt zwar an, über welchen Zeitraum interpoliert werden soll, aber nicht, wie lange die Animation genutzt wird. Du kannst ja einen Loop von einer Sekunde stundenlang laufen lassen. Für deinen Zweck musst Du also noch ein `delay` nutzen.

Alternativ könnten wir bei Character.animate noch einen vierten Parameter für die Dauer implementieren, der genau das gleiche bewirkt. Oder, wahrscheinlich noch besser, das `await` zur Funktion bringen und wenn man länger loopen will, lässt man das `await` einfach weg. Da müsste ich aber ein bisschen mehr schrauben...

**Comment by JirkaDellOro** [comment]
Geschraubt...!

Bitte testen und ggf. schließen

**Comment by Rina14** [comment]
Getestet und hat geklappt!
