### ISSUE TITLE
Inventar Item Amount abruf

### ISSUE THREAD

**Issue by SebiPf** [JirkaDellOro/FUDGE_Story#20]
Eine Methode einbinden die den amount der Items mitgibt. z.b. das der amount als zusätzliche variable einfach abgerufen werden kann wie z.b der Name eines Items. (hier ein Beispiel des syntaxes wie ich mir das vorgestellt hab: FS.Inventory.Potion.amount)

**Comment by Rina14** [comment]
Du möchtest also die `add`-Methode um einen Parameter erweitern, der die zu generierende Mengenangabe eines Items darstellt?

**Comment by JirkaDellOro** [comment]
Ich habe eine weitere Methode zum Inventar gefügt namens `getAmount (...)`. Der übergibt man eine ItemDefinition und erhält die Anzahl dieser Items im Inventar oder 0, wenn keine jener drin sind. Der Code entspricht intern Robins Vorschlag. Bitte testen und Issue schließen, wenn alles funktioniert.

**Comment by SebiPf** [comment]
Funktioniert danke
