### ISSUE TITLE
setMasterVolume() manipuliert die Gesamtlautstärke nicht mehr

### ISSUE THREAD

**Issue by Rina14** [JirkaDellOro/FUDGE_Story#22]
Beim Testen von setMasterVolume habe ich bemerkt, dass sich die Lautstärke nicht mehr verändert. Die Funktion wurde in zwei unterschiedlichen Projekten getestet und funktioniert in beiden nicht korrekt.
Bei einem der beiden Projekte (Tutorial) hat es vorher funktioniert, weshalb ich denke, dass es etwas mit den letzten Commits zu tun hat.

**Comment by JirkaDellOro** [comment]
Ich kann mich nicht erinnern, hier etwas gebastelt zu haben. Aber ich glaube Robin oder Du habt mal etwas mit Volume gemacht. Mach' mal diese Änderung rückgängig und schaue, ob das Problem weiter besteht. So können wir es ggf. schnell einkreisen.

**Comment by Rina14** [comment]
Ich bin gerade die Commits durchgegangen: Die Methode "setVolume()", die wir eingefügt hatten, hast Du schon abgeändert gehabt in setMasterVolume(). So konnte man dann auch problemlos die Gesamtlautstärke lauter oder leiser einstellen. Daher existiert die alte Methode gar nicht mehr.

**Comment by JirkaDellOro** [comment]
Das scheint jetzt widersprüchlich:
1. Beim Testen von setMasterVolume habe ich bemerkt, dass sich die Lautstärke nicht mehr verändert.
2. So konnte man dann auch problemlos die Gesamtlautstärke lauter oder leiser einstellen. 

Bedeutet das, dass es "damals" ging? Dann müsstest Du mal die Versionen seither auschecken und prüfen, ab welcher es nicht mehr geht.

**Comment by Rina14** [comment]
Genau, das bedeutet es und es wird ebenfalls durchgetestet. Ich sage dann Bescheid.

**Comment by JirkaDellOro** [comment]
Gibt es hier etwas Neues?

**Comment by Rina14** [comment]
Ja, die älteren FS-Versionen wurden nun getestet und der Fehler konnte nicht reproduziert werden. Daher wurden die Lauter- und Leiser-Funktionen nun in das Tutorial WS21 noch einmal eingebaut und überprüft. Es funktioniert soweit alles.
