### ISSUE TITLE
Animation Loop nicht zu stoppen

### ISSUE THREAD

**Issue by OrianeJoublin** [JirkaDellOro/FUDGE_Story#23]
Wenn am Anfang einer Szene eine lange Animation oder eine Animation Loop anfängt, geht sie auch in den nächsten Szenen weiter und ist nicht mehr zu stoppen.

Ich habe mit Riem schon eine Lösung gesucht und keine gefunden.

**Comment by JirkaDellOro** [comment]
Bitte Links zu Code und zur lauffähigen Novel hier posten.

**Comment by OrianeJoublin** [comment]
Das wäre die Novel, reicht das als Link?

https://github.com/OrianeJoublin/VisualNovel

**Comment by OrianeJoublin** [comment]
http://127.0.0.1:5500/Template/

Ich weiß nicht, ob der Link zur laufenden Novel bei dir funktionieren würde.

**Comment by OrianeJoublin** [comment]
https://orianejoublin.github.io/VisualNovel/ 

Okay, hier ist der .io Link

**Comment by JirkaDellOro** [comment]
Also, ich hatte schon reingeschaut und mich damit beschäftigt. Bislang gab es schlicht noch nicht den Bedarf, daher auch nicht die Funktionalität. Es gibt mehrere Lösungsoptionen:

1. Eine neue Animation definieren, die nur kurz läuft und diese dann einsetzen um zu stoppen. 
2. Den Charakter löschen und wieder neu einsetzen könnte auch gehen oder eine neue Pose mit dem gleichen Bild verwenden. Die Animation ist an die Pose gebunden.
3. Ich baue ein, dass man animate ohne Animation aufruft, das stoppt dann die aktuell laufende. Hierbei würde ich allerdings eine neue Version von FUDGE-Story erzeugen, und auch die jüngsten Änderungen von FUDGE mit einpflegen. Da müsstet ihr dann die entsprechenden Files bei euch austauschen.

Was darf es sein?

Übrigens: schön gemacht und super aufgeräumt das Projekt. Ist der Definitions-Folder Riems Idee?

Verbesserungsvorschläge:
- Zeile 22 kann weg, die macht nichts
- Überlegt, ob `S2_IntroPart2()` tatsächlich innerhalb von Teil 1 aufgerufen werden soll. In Main ist doch festgehalten, dass es als nächste Szene abgespielt wird. Das erscheint mir gedoppelt.

**Comment by Rina14** [comment]
Vom Bedarf weiß ich tatsächlich auch erst seit gestern. 

Zu den Lösungsoptionen: 

- Langfristig gesehen würde ich die 3. Option präferieren. Wäre das in so einer oder einer ähnlichen Form umsetzbar: `stopAnimation(<Die Animation, die gestoppt werden soll>)` statt `animate()`?

> Übrigens: schön gemacht und super aufgeräumt das Projekt. Ist der Definitions-Folder Riems Idee?

Nein, das war eine Frage seitens der Studis, ob das möglich ist, die ich lediglich bejahte und begrüßte :)

**Comment by JirkaDellOro** [comment]
> Nein, das war eine Frage seitens der Studis, ob das möglich ist, die ich lediglich bejahte und begrüßte :)    

Das sieht richtig gut aus!


 > stopAnimation(<Die Animation, die gestoppt werden soll>) statt animate()?  

Ich kann das ganz leicht jetzt schon machen und für die nächste Version vorhalten. Ich denke, es wäre jetzt vielleicht ungünstig, wenn im laufenden Kurs sich Versionen ändern. Die Animation ist ja an den Charakter und die Pose gebunden, daher müssen die beiden Informationen übergeben werden. Da die Funktionalität in `animate()` schon drinsteckt und die Parameterliste passt, würde ich es dabei belassen. Man kann dann die Zeile in seiner Novel kopieren und lediglich die Angabe der Animation durch `null` ersetzen. Alternativ könnte man die auch weglassen, aber das erscheint mir weniger explizit als `null`

**Comment by OrianeJoublin** [comment]
Ich hab tatsächlich gerade gemerkt, dass ich den Charakter auch einfach hiden kann. Aber für die Zukunft stimme ich Riem zu, das wäre eine praktische Funktion!
Vielen Dank für die Hilfe!

**Comment by JirkaDellOro** [comment]
Achso... ich dachte, die kleinen Samen sollten weiterhin da sein, aber sich nicht mehr bewegen. Hide ist andernfalls ohnehin die Lösung.

**Comment by Rina14** [comment]
Das dachte ich auch, aber gut, dass jetzt 'ne Lösung gefunden wurde.

**Comment by JirkaDellOro** [comment]
Ich habe das eingebaut und versehentlich auch gepusht.
