### ISSUE TITLE
CSS Textgröße an Canvas binden

### ISSUE THREAD

**Issue by OrianeJoublin** [JirkaDellOro/FUDGE_Story#26]
Ich hab jetzt einiges ausprobiert, aber ich schaffe es nicht, dass sich die Schriftgröße an die Größe des Hintergrundbildes anpasst und sich damit auch die Position des Texts nicht ändert. Also quasi, dass der Text (Position und Größe) immer proportional zur Canvasgröße bleibt, egal wie groß das Fenster/ Viewport ist. Soweit ich weiß, müsste das mit CSS machbar sein, wenn Speech hierarchisch unter Canvas angeordnet wäre, aber das kann ich selbst, soweit ich weiß, nicht ändern, weil das mit Fudge Story zusammenhängt? Ich hoffe, das ergibt Sinn. 

Code: https://github.com/OrianeJoublin/VisualNovel/tree/main/Template
Laufende Novel:  https://orianejoublin.github.io/VisualNovel/Template/index.html

**Comment by JirkaDellOro** [comment]
Hast Du mal z.B. bei solchen Posts geschaut?
https://stackoverflow.com/questions/16056591/font-scaling-based-on-width-of-container

**Comment by OrianeJoublin** [comment]
Ich habe mir den Artikel mal angeschaut, aber das hatte ich schon probiert. Ich verstehe, wie man die Schriftgröße proportional zur Viewport Width oder proportional zur Height gestaltet. Das Problem ist, dass die width und height des Canvas von Fudge Story angepasst wird, sodass das Aspect-Ratio des Canvas konstant bleibt (so habe ich das an der Stelle des Screenshots verstanden). Das heißt ich müsste die Font Size je nach Aspect-Ratio des Viewports propotional zur Width oder zur Height definieren. Ich weiß nicht, wie ich das mit CSS machen kann.
![image](https://user-images.githubusercontent.com/92022973/148681607-9cd7fddb-a9b9-4085-99be-29e61ab88e06.png)

**Comment by Rina14** [comment]
```
p {
 font-size: 2vw;
}
```

Hiermit sollte es klappen. Probier' das mal bitte aus und schließ den Issue, falls es geklappt hat.

**Comment by OrianeJoublin** [comment]
Hab es probiert uns es löst das Problem nicht.

**Comment by Rina14** [comment]
Ja, das auch sogar. Also bei mir hat es geklappt, wenn du möchtest können wir sonst noch einmal gemeinsam drüber schauen.

**Comment by JirkaDellOro** [comment]
Habt ihr das geklärt? In dem Fall bitte Issue schließen. Oder nochmal posten, was genau klemmt...

**Comment by Rina14** [comment]
da keine Rückmeldung und es bei mir so klappte wird der Issue geschlossen.
