### ISSUE TITLE
Transitions nur über die halbe Seite

### ISSUE THREAD

**Issue by OrianeJoublin** [JirkaDellOro/FUDGE_Story#27]
Hallo nochmal,
die Tranisition wird bei mir nur über die ober Hälfte der Seite abgespielt, wenn ich meinem Canvas die Große 1920x1080px gebe, statt 1200 x 720px. Das Format des Tranistionbilds ist allerdings sogar 1920x1080px. Carina hatte dasselbe Problem, als sie es bei ihrer Visual Novel ausprobiert hat (siehe Discord).

Code: https://github.com/OrianeJoublin/VisualNovel/tree/main/Template
Laufende Novel: https://orianejoublin.github.io/VisualNovel/

![image](https://user-images.githubusercontent.com/92022973/148726762-95e9c763-82bd-4e7b-9f7f-93e0635395ad.png)

**Comment by JirkaDellOro** [comment]
Ich hatte einmal kurz mir Riem darüber gesprochen, weiß aber nicht mehr, wie wir verblieben waren...

**Comment by Rina14** [comment]
@JirkaDellOro ohne Lösung verblieben, weil die Frage hier noch offen war, wie man überhaupt die Auflösung ändern kann.
