### ISSUE TITLE
Keyboard-Event kollidiert mit Input-Field  

### ISSUE THREAD

**Issue by corayana** [JirkaDellOro/FUDGE_Story#30]
Ich habe über die function hndKeyPress() festgelegt, dass sich das Inventar öffnet, wenn I geklickt wird.
Wenn ich nun in ein input-Feld i eingebe, öffnet sich das Inventar, statt ein "i" reinzuschreiben. Gibt es einen vorgesehenen Weg, wie ich das umgehen kann?

[Meine Visual Novel](https://corayana.github.io/VisualNovel/)
[Szene mit input-field](https://github.com/corayana/VisualNovel/blob/main/Source/Scenes/Intro.ts)
[Menu mit function hndKeyPress()](https://github.com/corayana/VisualNovel/blob/main/Source/Definitions/Menu.ts)

**Comment by JirkaDellOro** [comment]
Ok, danke. Das hat geholfen schnell an die richtige Stelle zu kommen. Ich habe FUDGE-Story aktualisiert, bitte testen.

**Comment by corayana** [comment]
Super, das hats getan! Dankeschön :)
