### ISSUE TITLE
--- Flashing backgrounds in Introduction, transitions playing incorrectly from black, tv-lines covering the screen ---

### ISSUE THREAD

**Issue by Hanhan139** [JirkaDellOro/FUDGE_Story#38]
--- Either this: ---
(will be referred to as LineError)

![image](https://user-images.githubusercontent.com/64596931/212140334-f2ff6e29-794d-40b5-8830-fa9a37b784d9.png)

--- Or flashing from a black screen that shouldn't be there --
(FlashBlackError)

Not to say I don't appreciate these kind of horror shaders and they give the image more visual interest,
but if it's not happening on command it's a bit of an issue.
So I wrote an issue! There's more to come;

This one particularly happens after the opening "cutscene" after the second sentance.
I'm using multiple backgrounds to achieve small fog effects and transitions from one picture to another (see below).
Specifically in the change from picture 4 to 5 and 5 to 6.

All other transitions work, and the LineError is gone when i simply use update(1); without an alpha channel.
But the FlashBlackError persists. How do I solve it? 

FIle: scn_Intro.ts
Code:

```
        await ƒS.Speech.tell(characters.HER, "Now, the only thing that’s left before I leave you, is…");
        await ƒS.Speech.clear();
        await ƒS.Speech.hide();
        await ƒS.update(1);

        await ƒS.Location.show(backgrounds.BG_Intro_Night3);    
        await ƒS.update(3, transitions.dotscrollRL.alpha, 0.5);

        await ƒS.Character.animate(
          characters.HER, characters.HER.pose.default_happy, anim_fadeInFromBlack());

        await ƒS.update(0.1);

        await ƒS.Location.show(backgrounds.BG_Intro_Night4);    
        await ƒS.update(1, transitions.fade.alpha, 0.1);
        await ƒS.Location.show(backgrounds.BG_Intro_Night5);    
        await ƒS.update(1, transitions.fade.alpha, 0.1);

        await ƒS.Speech.tell(characters.HER, "BANNING you!!!");
```

--- Backgrounds ---

![BG_night_06](https://user-images.githubusercontent.com/64596931/212139198-24c2716a-bf91-4ea9-b752-208b9d347256.png)
![BG_night_05](https://user-images.githubusercontent.com/64596931/212139197-cea78706-bc22-45ca-aae9-724fe9b48ff4.png)
![BG_night_04](https://user-images.githubusercontent.com/64596931/212139196-daee1bc0-68f8-4ed1-96cc-e70a33bfa13b.png)
![BG_night_03](https://user-images.githubusercontent.com/64596931/212139193-3d3416f6-0242-42c4-9e87-c7f61192e782.png)
![BG_night_02](https://user-images.githubusercontent.com/64596931/212139189-c9df1875-12f7-45d5-a95c-3aa87a899137.png)
![BG_night_01](https://user-images.githubusercontent.com/64596931/212139182-34a0bf49-4b76-4a1f-b973-1c03bbcd717c.png)

**Comment by Rina14** [comment]
@Hanhan139 bitte neue FS-Version ziehen!
