### ISSUE TITLE
Splash.png wird nicht angezeigt; Fehlermeldung

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/FUDGE_Story#42]
Hallo zusammen,

mein Splash.png wird mir nicht angezeigt, wenn ich es über den Pages-Link teste. Lokal wird das Bild angezeigt.
Hier die Fehlermeldung.
<img width="365" alt="image" src="https://user-images.githubusercontent.com/56167839/218438543-f6068ab5-90f0-41be-9728-756e4113f589.png">

**Comment by FrankeSa** [comment]
Hier noch mein Pages-Link: https://frankesa.github.io/vn_repo_sarah/The_Pingu/SarahsNovel.html

**Comment by JirkaDellOro** [comment]
Nach dieser Präzisierung kann ich immerhin Tipps geben:
1. der Pages-Server ist deutlich strikter als der lokale. Prüfe Groß-/Kleinschreibung, nutze keine Leer- und Sonderzeichen außer `_`, Bennene alles auf Englsich.
2. prüfe, ob dein Localhost und Pages das gleiche Wurzelverzeichnis nutzen. Oft wird getestet mit dem Localhost tief in der Hierarchy, Pages aber startet auf der Wurzel des Repositories.

**Comment by FrankeSa** [comment]
Also, ich habe den Fehler gefunden.
In meiner CSS-Datei war das Bild so angelegt:  background-image: url("**/**Images/Splash.png");    Das hat die Fehlermeldung verursacht bzw. das Bild konnte nicht gefunden werden.

Richtig ist aber  background-image: url("Images/Splash.png");   -ohne den Schrägstrich vor Images.
Jetzt konnte das Bild geladen werden.
Danke, für dein Tipps, Jirka.
