### ISSUE TITLE
Szenenstruktur

### ISSUE THREAD

**Issue by FrankeSa** [JirkaDellOro/FUDGE_Story#43]
Hallo,

ich weiß das hatten wir in der Vorlesung aber ich kann mich leider nicht mehr an den Code erinnern.... :(
Ich habe ein Punktesystem und wenn ich 5o pkt. gesammelt habe, dann soll das Happy End aufgerufen werden ansonsten das "normale" Ende.

Wie sage ich nun das eine nächste Szene abgespielt wird?
In der Main habe ich bei Szene 15 als next keine Szene angegeben, trotzdem wird Szene 16 abgespielt.
In Szene 15 habe ich gesagt, wenn 50 Pkt. erreicht sind, dann soll Szene 16 abgespielt werden return scene16(). Ansonsten soll es einen Text ausgeben Text.Print.

https://frankesa.github.io/vn_repo_sarah/The_Pingu/SarahsNovel.html
https://github.com/FrankeSa/vn_repo_sarah

**Comment by Rina14** [comment]
ach ja und zukünftig bitte Direktlinks zum entsprechenden Code hier verlinken, das erspart die Suche nach diesen :)

**Comment by FrankeSa** [comment]
Super, Danke Riem! Es hat funktioniert. 
Dann war ich doch recht nahe dran...
