### ISSUE TITLE
Musik stoppen

### ISSUE THREAD

**Issue by baohannguyen** [JirkaDellOro/FUDGE_Story#46]
Gibt es eine Möglichkeit die Musik in eine Szene zu stoppen? Ich hab grade das Problem, dass wenn ich in eine Szene Musik abspiele das sie direkt in der nächsten Szene weiterspielt und wenn ich in der nächsten Szene eine andere Musik abspielen möchte, hört man trotzdem noch die Musik von der vorherigen Szene, d.h. die Musik von beiden überschneiden sich.

**Comment by Rina14** [comment]
Ja, indem du den Sound mit der Fade-Methode in der jeweiligen Szene am Ende auf 0 (volume) setzt.

**Comment by baohannguyen** [comment]
Ah ok hat funktioniert, danke dir! :)
