### ISSUE TITLE
CSS Modifikationen werden vor dem Laden der Szene angezeigt

### ISSUE THREAD

**Issue by Rina14** [JirkaDellOro/FUDGE_Story#9]
Der Screen zeigt die CSS Modifikationen u.a. vom Textbalken sofort an; dieser sollte aber eigentlich erst zu Beginn der Szene bzw. nach der Transition oder wenn Text dargestellt werden soll, angezeigt werden.
<br>Siehe Beispielbild.<br>
![text bar](https://user-images.githubusercontent.com/32566154/116798073-6ea14a80-aaec-11eb-991e-a695ae25a7ac.png)

**Comment by JirkaDellOro** [comment]
Dann musst Du in vorher ausschalten und danach einschalten.

**Comment by Rina14** [comment]
hm, das hatte ich in meinem Prototypen auch. Sollte aber eigentlich keine Dauerlösung sein, dachte ich.

**Comment by JirkaDellOro** [comment]
Vielleicht habe ich noch nicht verstanden, was genau Du möchtest. Es gibt keinen Automatismus, denn es kann ja auch sein, dass Du eine Transition im Bild haben möchtest, die Speech (um den Balken geht es, glaube ich) bleibt aber stehen.

**Comment by Rina14** [comment]
Speech.hide() & Speech.show()
